### ISSUE TITLE
dup overrides VIRTUAL_HOST environment variable settings in "env"

### ISSUE THREAD

**Issue by ncraike** [girvo/dup#10]
Even if you explicitly set a `VIRTUAL_HOST` variable in `.up.json`'s "env" object, Dup overrides the value with `<project>.docker`.

**Comment by girvo** [comment]
@ncraike This should be really simple to fix; in the `startWeb` proc, adjust the order the `env` flags are defined. Simple! :)

**Comment by girvo** [comment]
@dotstormz If you want to take a look at fixing this, check the `startWeb` proc on line 189, specifically looking at line 196 where the command is built!

**Comment by girvo** [comment]
Resolved

**Comment by ncraike** [comment]
Thanks for the fix!
