### ISSUE TITLE
Automatically start nginx-proxy if it's not running

### ISSUE THREAD

**Issue by dotstormz** [girvo/dup#3]
https://github.com/jwilder/nginx-proxy

**Comment by girvo** [comment]
This feature will allow handling of `nginx-proxy` automatically, to allow easier web development with `dnsmasq`. This will mean you can easily run multiple web containers side-by-side without port conflicts, by leveraging the `VIRTUAL_HOST` env var (that `dup` already sets)

**Comment by girvo** [comment]
As #10 is now fixed, and the refactoring has been completed, we should revisit this and whether it's required. Closing for now, perhaps will look at it once we've moved to using the Docker socket instead of `execCmd`
