### ISSUE TITLE
Create homebrew and debian/yum packages

### ISSUE THREAD

**Issue by girvo** [girvo/dup#6]
Need to do research into the best way of packaging up `.deb` and `.rpm` files?

**Comment by girvo** [comment]
@ncraike Have you had any experience working with Linux package systems?

**Comment by ncraike** [comment]
Some with rpm, though it was at Netbox Blue and so very particular to their
setup.

And a teeny tiny bit when working on an issue for Docker (part of a
hackathon they ran, and how I got my whale shirt).

Could probably give it a go?

Maybe target Homebrew first? That'd solve the pcre issue sorta. :P

**Comment by girvo** [comment]
@ncraike Yeah, my plan is to handle `homebrew` first and then see how hard it is to "port" that to `deb` and `rpm`

**Comment by girvo** [comment]
This is probably unneeded at this point, I'll close it and we can revisit in the future.
