### ISSUE TITLE
Allow a port to be specified for MySQL and Postgres DB containers

### ISSUE THREAD

**Issue by dotstormz** [girvo/dup#7]
If you have several projects running ports conflict.

**Comment by dotstormz** [comment]
@girvo Hey man is this something that I can attempt to add?

**Comment by girvo** [comment]
Definitely, the code is pretty straightforward, you'll want to get Nim up and running (don't use the homebrew version, moves too quick as a language for it to be up to date, follow the compilation steps on the site)

**Comment by girvo** [comment]
To update, @ncraike has temporarily disabled the hard-coded ports for the databases, until we get around to writing a proper solution for this. See PR #9 for the relevant changes

**Comment by ncraike** [comment]
The temporary solution has the caveat that now you can't connect to the database easily from the host (eg with Sequel Pro, Postico) as the database container's port isn't mapped to any public port on the Docker host. You can probably work around this by starting/configuring the database container yourself, but it's a bit of hassle.

**Comment by girvo** [comment]
This now finds a random open high-port and binds the database to it instead. Closing this as fixed :)
