### ISSUE TITLE
Add "exec" command for handling Symfony "app/console"

### ISSUE THREAD

**Issue by girvo** [girvo/dup#8]

**Comment by girvo** [comment]
@dotstormz @roura356a @ncraike 

Thoughts on this feature? Do we really need it, considering that the syntax will need to be identical to `docker exec` anyway? Seems sort of un-needed, aside from `docker exec [-i] [-t] <name> <command>` becoming `dup exec [-i] [-t] [web|db] <command>`...

**Comment by rouralberto** [comment]
In one side would be good to have all integrated in dup, but... if the syntax is identical to docker I feel is unnecessary IMO.

**Comment by girvo** [comment]
Agreed, @roura356a
